name = "cors-proxy"
main = "worker.js"
compatibility_date = "2023-01-01"

# Specify the account ID (you'll need to replace this with your own)
# account_id = "your-account-id"

# Use the 'workers-dev' environment by default
workers_dev = true

# Route pattern for custom domains (if you have one)
# routes = [
#   { pattern = "cors-proxy.yourdomain.com/*", zone_id = "your-zone-id" }
# ] 